### PR TITLE
core: event: Fix typo in mk_event_select.c.

### PR DESCRIPTION
**Pull request by igorpeshansky**
Fixes a type error introduced in #359:
```
…/mk_core/mk_event_select.c:370:34: error: invalid type argument of '->' (have 'struct mk_event')
  370 |             if (ctx->fired[index]->fd == event->fd) {
      |                                  ^~
…/mk_core/mk_event_select.c:378:34: error: incompatible types when assigning to type 'struct mk_event' from type 'struct mk_event *'
  378 |     ctx->fired[loop->n_events] = event;
      |                                  ^~~~~
```

### CODE REVIEW

**Comment by igorpeshansky** [comment]
@edsiper Could you take a quick look when you have a chance?

**Comment by edsiper** [comment]
assigning to @leonardo-albertovich for review.

**Comment by leonardo-albertovich** [comment]
Actually, the select backend is special in how it handles the `fired` array which you can see [here](https://github.com/monkey/monkey/blob/master/mk_core/mk_event_select.c#L424) so the code in question would be correct unless I'm wrong.

However, last time I checked the select backend was severely lacking, broken design wise (eg. how `events` is indexed using the file descriptor [here](https://github.com/monkey/monkey/blob/master/mk_core/mk_event_select.c#L133) which could exceed the preallocated size or how `max_fd` is set to match the highest fd but never scaled back [here](https://github.com/monkey/monkey/blob/master/mk_core/mk_event_select.c#L134))  and in disuse so if my opinion is that it should be scrapped and re-written to comply with how the rest of the backends work in order to be viable.

**Comment by edsiper** [comment]
I agree to merge the compiler fix, however this backend is not supported and lack of scalability features.,
